### ISSUE TITLE
Readme has incorrect git command

### ISSUE THREAD

**Issue by brandonscript** [apigee/Sweetlime#3]
The git install command on the readme has a couple syntax errors. Should be:

```
git clone git@github.com:apigee/Sweetlime.git '~/Library/Application\ Support/Sublime\ Text\ 3/Packages/ApigeeSweetLime'
```

**Comment by girishbr** [comment]
because of the space? Quotes are required only if you don't want to escape the spaces in the path. In my git command the spaces in the path are escaped with \  - infact you can cd to ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/ApigeeSweetLime.
